services:
  postgres:
    image: postgres:16-alpine
    container_name: milearnapp_postgres
    restart: always
    environment:
      POSTGRES_USER: milearn
      POSTGRES_PASSWORD: milearn_password
      POSTGRES_DB: milearndb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/services/db/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U milearn -d milearndb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
